# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.0'

gem 'erubis'
gem 'minitest'
gem 'minitest-reporters'
gem 'pry'
gem 'rack-test'
gem 'redcarpet'
gem 'sinatra'
gem 'sinatra-contrib'
